### ISSUE TITLE
nano.use is not a function... Readme.md not up-to-date? 

### ISSUE THREAD

**Issue by wandonye** [apache/couchdb-nano#183]
## Expected Behavior

The codes below should work according to README.md
```
const nano = require("nano")(`http://${couchdb.username}:${couchdb.password}@${couchdb.host}`);

const db = nano.use(`${couchdb.userDB}`)
```
## Current Behavior

 It gives error `nano.use is not a function`

## Possible Solution

Maybe update the sample codes in readme into
```
const alice = nano.server.db.use('alice');
alice.insert({ happy: true }, 'rabbit').then((body) => {
  // do something
});
```
## Steps to Reproduce (for bugs)

Just try:
```
const nano = require("nano")(`http://${couchdb.username}:${couchdb.password}@${couchdb.host}`);
const alice = nano.use('alice');
alice.insert({ happy: true }, 'rabbit').then((body) => {
  // do something
});
```
The second line will give error

## Your Environment

* Version used: 8.1.0
* Browser Name and version:
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

**Comment by juanp123** [comment]
Ran into the above problem and it is repeatable..

Using the initial example for reference: 
```
const nano = require("nano")(`http://${couchdb.username}:${couchdb.password}@${couchdb.host}`);

const db = nano.use(`${couchdb.userDB}`)
```
The missing `.use(...)` is caused by an invalid URL.  

in ` module.exports = exports = function dbScope (cfg)`
the return is as follows (last two lines)
```
  const db = maybeExtractDatabaseComponent()

  return db ? docModule(db) : serverScope

```
Haven't dug into the details of these last lines but can say that if the url is invalid, it appears it will not return the serverScope which contains the `use(...)` 

 In my case `process.env.SOMEVAR` was being used to set the url but was wasn't configured properly so the url was getting null or undefined values.  Once that was fixed, `.use(...)` exists.

Just leaving this as a reference for others with that have the same issue.
