### ISSUE TITLE
Support for _find (mango queries)

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#26]
[Original issue](https://github.com/dscape/nano/issues/329)

__chrisfosterelli__
CouchDB 2.0 has a _find route that accepts mango queries. We're using the developer preview of Couch 2 and it'd be great if nano could expose this route!

Currently we have to work around nano to use these.

__chirsfosterelli__
Something like this might work:
```javascript
const couch = nano(url)
couch.use(db).mango.find({ ... }, (err, results) => {
  // do your thing
})
```

**Comment by kokarn** [comment]
This would indeed be great

**Comment by glynnbird** [comment]
We have support for this in the [nodejs-cloudant](https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L152) library. Mango was originally a cloudant-only thing but since CouchDB 2.0 has it in, then the `find` and related functions should really be in this project now (and can then be removed from the Cloudant library).

**Comment by mojari** [comment]
I want to use const couch = nano(url)
couch.use(db).mango.find({ ... }, (err, results) => {
  // do your thing
}).
Is this issue is resolved? Can you share the step. I have to use nano or any other library. I need sample code for the same.

Thanks

**Comment by Weber-D** [comment]
How to use this method? There seems a complete lack of documentation. And also this examples doesn't fit in typescript: 

```ts
let n = <nano.ServerScope>nano(connectionString);
let db=n.db.use('mydb')
db.find(query, (cb:nano.Callback<nano.MangoResponse<{}>>)=>{
    // what goes here? cb is a callback, doesn't make sense for me here
})
```
