### ISSUE TITLE
Perform search over POST too

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#32]
[Original issue](https://github.com/dscape/nano/issues/338)

__TheHominid__
A too long search query results in an error 400 from couchDB (due to GET url length limitations), however if the same query is sent inside the body with a POST call, couchDB works properly.
From the code it seems that nano can only perform search operations over GET and not POST.

**Comment by popojargo** [comment]
@glynnbird Hi Glynn! I really need to make a call on _all_docs using the POST method. I would like to implement this feature in nano. 

I'm wondering what would be the best approach to implement this new route:

1. Should I make the nano.db.list configurable with a parameter to decide if we use GET or POST
2. Create a new function (perhaps, nano.db.listWithPost)
3. Always pass the keys in the body and always use the GET instead of POST. 

For 3, I fear that it could cause some problems if people have custom proxies that limit the method/endpoints accessible.

Let me know what you think!

**Comment by glynnbird** [comment]
There's already an API call do do that. It's called `fetchDocs` !


https://github.com/apache/couchdb-nano/blob/master/lib/nano.js#L585-L597

**Comment by popojargo** [comment]
Ah my bad! Thanks glynn! I think we can also close this issue.
