### ISSUE TITLE
Couchdb-lucene support / interoperability with Cloudant

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#7]
[Original issue](https://github.com/dscape/nano/issues/263)

__homerjam__
Hi,

I've been using pouchdb with a plugin to allow couchdb-lucene to be used locally and cloudant in production - I presume this could be done by extending nano.

However as both extensions are very popular would you consider adding dedicated support for couchdb-lucene also? It would be nice to have a clean, maintained implementation.

Thanks

__dscape__
Would consider it, can you propose how this would look like in your view?

__homerjam__
I guess something like:
```javascript
// usage

var nano = require('nano');

var db = nano({
    url: 'http://localhost:5984/foo',
    searchVendor: nano.CLOUDANT_SEARCH || nano.LUCENE_SEARCH
);


// in nano.js

// declare constants (after line 12)
nano.CLOUDANT_SEARCH = 'cloudant';
nano.LUCENE_SEARCH = 'lucene';

// choose viewPath style (around 474)
var viewPath;

if (meta.type === 'search' && cfg.searchVendor === nano.LUCENE_SEARCH) {
    viewPath = '/_fti/local/' + dbName + '/_design/' + ddoc + '/' + viewName;
} else {
    viewPath = '_design/' + ddoc + '/_' + meta.type + '/'  + viewName;
}
```

The trouble is that couchdb-lucene uses a different path - normally the database name is at the start but instead it comes after the /_fti/local/ prefix. So this would require some further modification in the relax() function I think.

**Comment by carlosduclos** [comment]
There is a pull request in the original issue, I asked the author to port it to this repository.

**Comment by homerjam** [comment]
@dscape could you comment on the suitability of the changes I made [here](https://github.com/dscape/nano/pull/272/files)?

I'm wondering if it's worth me porting the PR as it sat there unloved for a while before!

Personally I'm looking to move off Cloudant due to their pricing changes and forcing customers off the old plans (by dropping support next year). This would give me and maybe others(?) a reasonable alternative in couchdb-lucene.

**Comment by janl** [comment]
Should have happened.

**Comment by homerjam** [comment]
😢
